version: "3"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ws_u
      POSTGRES_PASSWORD: ws_p
      POSTGRES_DB: ws_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data